---
all:
  children:
    local:
      hosts:
        localhost:
          ansible_connection: local
          ansible_python_interpreter: /usr/bin/python3
    k8s_cluster:
      hosts:
        docker-desktop:
          ansible_connection: local
          k8s_context: docker-desktop
          k8s_namespace: webapp
